/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// src/main.ts
var main_exports = {};
__export(main_exports, {
  default: () => TreeDiagramPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian3 = require("obsidian");

// src/TreeDiagramMarkdownRenderChild.ts
var import_obsidian = require("obsidian");

// src/node.ts
var Node = class {
  constructor(name, depth, parent = null, isLast = false) {
    this.name = name;
    this.depth = depth;
    this.parent = parent;
    this.children = [];
    this.isLast = isLast;
  }
  addChild(child) {
    if (this.children.length > 0)
      this.children[this.children.length - 1].isLast = false;
    this.children.push(child);
    child.setIsLast(true);
    child.setParent(this);
    child.setDepth(this.depth + 1);
  }
  setParent(p) {
    this.parent = p;
  }
  setIsLast(v) {
    this.isLast = v;
  }
  setDepth(d) {
    this.depth = d;
  }
};

// src/util.ts
var EDGE = "\u251C\u2500\u2500 ";
var CORNER = "\u2514\u2500\u2500 ";
var LINE = "\u2502   ";
var BLANK = "    ";
function parseLine(text) {
  let depth = 0;
  let index = 0;
  let name = "";
  while (text.charAt(index) === "	") {
    depth++;
    index++;
  }
  name = text.substring(index);
  return {
    depth,
    name
  };
}
function parseInput(source) {
  var _a;
  let lines = source.trim().split("\n");
  if (lines.length == 0)
    return null;
  let root;
  let lastNode;
  let { depth, name } = parseLine(lines[0]);
  root = new Node(name, 0, null, true);
  lastNode = root;
  for (let i = 1; i < lines.length; i++) {
    let { depth: depth2, name: name2 } = parseLine(lines[i]);
    if (depth2 == 0) {
      continue;
    }
    let node = new Node(name2, depth2);
    if (node.depth === lastNode.depth) {
      (_a = lastNode.parent) == null ? void 0 : _a.addChild(node);
    } else if (node.depth > lastNode.depth) {
      lastNode.addChild(node);
    } else {
      let diff = lastNode.depth - node.depth;
      let parent = lastNode.parent;
      if (parent == null)
        throw Error("parent is null!");
      while (diff > 0) {
        parent = parent.parent;
        if (parent == null)
          throw Error("parent is null!");
        diff--;
      }
      parent.addChild(node);
    }
    lastNode = node;
  }
  return root;
}
function treeView(root) {
  let output = [];
  let queue = [...root.children];
  output.push(root.name);
  while (queue.length > 0) {
    let node = queue.shift();
    if (node === void 0) {
      throw Error("node is undefined!");
    }
    queue = [...node.children, ...queue];
    let line = "";
    let n = node.parent;
    while (n) {
      if (n === root)
        break;
      if (n.isLast === true) {
        line = BLANK + line;
      } else {
        line = LINE + line;
      }
      n = n.parent;
    }
    line = line.concat(node.isLast ? CORNER : EDGE);
    line = line.concat(node.name);
    output.push(line);
  }
  return output;
}

// src/TreeDiagramMarkdownRenderChild.ts
var import_obsidian2 = require("obsidian");
var TreeDiagramMarkdownRenderChild = class extends import_obsidian.MarkdownRenderChild {
  constructor(plugin, source, containerEl, ctx) {
    super(containerEl);
    this.plugin = plugin;
    this.source = source;
    this.ctx = ctx;
  }
  async onload() {
    let root;
    let output = [];
    let markdown;
    root = parseInput(this.source);
    if (root != null) {
      output = treeView(root);
    }
    markdown = ["```", "\n", output.join("\n").trim(), "\n```"].join("");
    await import_obsidian2.MarkdownRenderer.render(this.plugin.app, markdown, this.containerEl, this.ctx.sourcePath, this);
  }
};

// src/main.ts
var TreeDiagramPlugin = class extends import_obsidian3.Plugin {
  async onload() {
    this.registerMarkdownCodeBlockProcessor("tree", async (source, el, ctx) => {
      ctx.addChild(new TreeDiagramMarkdownRenderChild(this, source, el, ctx));
    });
  }
  onunload() {
  }
};


/* nosourcemap */